version: 2.1

parameters:
  cimg-base-tag:
    type: string
    default: "oas-3855-54403bbfeb0d5e419b000bb9f062fba367039530"

executors:
  go-executor:
    docker:
      - image: arangodboasis/cimg-base:<< pipeline.parameters.cimg-base-tag >>

jobs:
  build:
    executor: go-executor
    environment:
      CIMGBASETAG: << pipeline.parameters.cimg-base-tag >>
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "$DOCKER_REGISTRY_PASSWORD" | base64 -d | docker login -u "$DOCKER_REGISTRY_USER" --password-stdin "$DOCKER_REGISTRY_HOST"
      - run: docker run --rm --privileged tonistiigi/binfmt:latest --install "$BUILDX_PLATFORMS"
      - run: ./build-images.sh
      - slack/notify:
          event: fail
          template: basic_fail_1

orbs:
  slack: circleci/slack@4.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: arangodboasis

