version: 2.1

orbs:
  # cimg: circleci/cimg@0.3.3
  cimg: circleci/cimg@dev:08bf03048fedc04c38b6557e4878b5bad26dcf12
  slack: circleci/slack@4.12.1
  gh: circleci/github-cli@2.2.0
  aws-cli: circleci/aws-cli@4.0.0

parameters:
  cron:
    type: boolean
    default: false

workflows:
  automated-wf:
    when: << pipeline.parameters.cron >>
    jobs:
      - check-feed:
          context:
            - cimg-publishing
  main-wf:
    when: << pipeline.parameters.cron >>
    jobs:
      - cimg/build-and-deploy:
          name: "Staging"
          docker-namespace: ccitest
          docker-repository: golang
          publish-branch: test
          filters:
            branches:
              ignore:
                - main
          post-steps:
            - slack/notify:
                branch_pattern: release-v.+
                event: pass
                mentions: "@jalexchen"
                template: basic_success_1
          context: cimg-publishing
      - cimg/build-and-deploy:
          name: "Deploy"
          docker-repository: go
          filters:
            branches:
              only:
                - main
          post-steps:
            - slack/notify:
                branch_pattern: main
                event: fail
                mentions: "@images"
                template: basic_fail_1
          context: cimg-publishing
  docker-wf:
    jobs:
      # - aws-ecr-write:
      #     context: cimg-publishing
      - aws-ecr-read:
          # requires:
          #   - aws-ecr-write
          context: cimg-publishing
      - verify:
          requires:
            - aws-ecr-read
          context: cimg-publishing
      - copy:
          requires:
            - verify
          context: cimg-publishing

jobs:
  check-feed:
    docker:
      - image: cimg/base:2023.01
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "f8:07:0f:f6:b5:eb:57:ae:be:4d:2f:2d:be:70:8f:ff"
      - run:
          name: SSH config to pull and push project
          command: |
            ssh-add -D
            ssh-add ~/.ssh/id_rsa_f8070ff6b5eb57aebe4d2f2dbe708fff
            ssh-keygen -f ~/.ssh/id_rsa_f8070ff6b5eb57aebe4d2f2dbe708fff -y > ~/.ssh/id_rsa_f8070ff6b5eb57aebe4d2f2dbe708fff.pub
            echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFHZoU4/njm1peseKCHfY4igdb4cbVwK16ADNlIoj6Ch secops+cpe-image-bot@circleci.com" > ~/.ssh/allowed_signers
      - run:
          name: Run git config
          command: |
            cat \<<'EOF' >> ~/githelper.sh
              #!/usr/bin/env bash
              echo username=$GIT_USERNAME
              echo password=$IMAGE_BOT_TOKEN
            EOF

            git config --global user.email "secops+cpe-image-bot@circleci.com"
            git config --global user.name "cpe-image-bot"
            git config --global user.signingkey "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFHZoU4/njm1peseKCHfY4igdb4cbVwK16ADNlIoj6Ch"
            git config --global gpg.ssh.allowedSignersFile ~/.ssh/allowed_signers
            git config --global url."https://github.com".insteadOf ssh://git@github.com
            git config --global url."https://github.com/".insteadOf git@github.com:
            git config --global credential.helper "/bin/bash ~/githelper.sh"
            git config --global gpg.format ssh
            git config --global commit.gpgsign true
            git submodule sync
      - gh/setup:
          token: IMAGE_BOT_TOKEN
      - run:
          name: Run version update script
          command: |
            sudo chmod +x goFeed.sh
            git submodule update --init --recursive
            ./goFeed.sh

  aws-ecr-write:
    docker:
      - image: cimg/aws:2023.07.1
    steps:
      - checkout
      - setup_remote_docker
      - aws-cli/setup:
          role_arn: arn:aws:iam::483285841698:role/cpe-ecr-write
          role_session_name: "push-to-ecr"
      - run:
          command: |
            aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin 483285841698.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - cimg/build-images:
          docker-namespace: "483285841698.dkr.ecr.us-east-1.amazonaws.com"
          docker-repository: go
          publish-branch: test

  aws-ecr-read:
    docker:
      - image: cimg/aws:2023.07.1
    steps:
      - checkout
      - setup_remote_docker
      - aws-cli/setup:
          region: ${AWS_DEFAULT_REGION}
          role_arn: arn:aws:iam::483285841698:role/cpe-ecr-write
          role_session_name: "pull-from-ecr"
      - run:
          command: |
            curl -L https://github.com/regclient/regclient/releases/latest/download/regctl-linux-amd64 >regctl
            sudo chmod 755 regctl
            sudo mv regctl /usr/local/bin/
      - run:
          name: Sign into ECR
          command: |
            aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin 483285841698.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - run:
          name: Retrieve and save digests associated with pushed tags
          command: |
            mkdir -p /tmp/registry
            source GEN-CHECK
            tagList=("$(regctl tag ls 483285841698.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/go)")
            for tag in "${GEN_CHECK[@]}"; do
              tag=${tag%#*}
              cleanTag=${tag%.*}

              for registryTag in ${tagList[*]}; do
                if ! [[ "$registryTag" =~ $cleanTag ]]; then
                  continue
                else
                  manifestFile=$(docker buildx imagetools inspect 483285841698.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/go:"${registryTag}" --format "{{json .Manifest}}")
                  echo "$manifestFile" > "/tmp/registry/$registryTag-manifest.json"
                fi
              done
            done

            echo "{}" > /tmp/registry/metadata.json
            for file in /tmp/registry/*-manifest.json; do
              dirtyTag=${file%-*}
              tag=$(echo $dirtyTag | cut -d / -f4)
              jq --arg tag "$tag" --slurpfile input "$file" '. += { ($tag): $input }' /tmp/registry/metadata.json > tmp.json && mv tmp.json /tmp/registry/metadata.json
            done

      - store_artifacts:
          path: /tmp/registry

      - persist_to_workspace:
          root: /tmp/registry
          paths:
            - "*-manifest.json"
            - "metadata.json"

  verify:
    docker:
      - image: cimg/aws:2023.07.1
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/registry
      - setup_remote_docker
      - aws-cli/setup:
          region: ${AWS_DEFAULT_REGION}
          role_arn: arn:aws:iam::483285841698:role/cpe-ecr-write
          role_session_name: "pull-and-verify"
      - run:
          name: Download regctl
          command: |
            curl -L https://github.com/regclient/regclient/releases/latest/download/regctl-linux-amd64 >regctl
            sudo chmod 755 regctl
            sudo mv regctl /usr/local/bin/
      - run:
          name: Sign into ECR
          command: |
            aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin 483285841698.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - run:
          name: Verify digests
          command: |
            touch noMatch.txt
            check=$(cat noMatch.txt)
            tagList=$(jq -r 'keys[]' /tmp/registry/metadata.json)

            for tag in $tagList; do
              comparisonSHA=$(jq -r ".[\"$tag\"][0].digest" /tmp/registry/metadata.json)
              registrySHA=$(regctl image digest 483285841698.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/go:"${tag}")

              if ! [[ $comparisonSHA == $registrySHA ]]; then
                echo "metadata.json $tag: $comparisonSHA \n
                registry $tag: $registrySHA" >> noMatch.txt
              fi
            done

            if [[ -z $check ]]; then
              echo "All digest checks passed"
            else
              echo "Please check noMatch.txt. There are digests that do not match"
              exit 1
            fi
  copy:
    docker:
      - image: cimg/aws:2023.07.1
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/registry
      - setup_remote_docker
      - aws-cli/setup:
          region: ${AWS_DEFAULT_REGION}
          role_arn: arn:aws:iam::483285841698:role/cpe-ecr-write
          role_session_name: "copy"
      - run:
          name: Download regctl
          command: |
            curl -L https://github.com/regclient/regclient/releases/latest/download/regctl-linux-amd64 >regctl
            sudo chmod 755 regctl
            sudo mv regctl /usr/local/bin/
      - run:
          name: Sign into ECR and Docker
          command: |
            # Log into ECR for source manifests
            aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin 483285841698.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
            # Log into Dockerhub
            echo "$TEMP_DOCKER_TOKEN" | docker login -u "$TEMP_DOCKER_USER" --password-stdin
      - run:
          name: Copy manifests
          command: |
            tagList=$(jq -r 'keys[]' /tmp/registry/metadata.json)

            for tag in $tagList; do
              regctl image copy 483285841698.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/go:${tag} ferriswh33l/node-dev:${tag}
            done
      # - run:
      #     name: Verify
      #     command: |
      #       touch verification.txt
      #       verification=$(cat verification.txt)
      #       tagList=$(jq -r 'keys[]' /tmp/registry/metadata.json)
      #       for tag in $tagList; do
      #         verify=$(regctl manifest diff 483285841698.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/go:${tag} ferriswh33l/node-dev:${tag})

      #         if ! [[ -z $verify ]]; then
      #           echo "There are differences in the manifest for the $tag tag"
      #           echo "$tag" >> verification.txt
      #         fi
      #       done

      #       if [[ -z $verification ]]; then
      #         echo "Please check verification.txt for differences in manifests"
      #         exit 1
      #       else
      #         echo "Manifest check succeeded"
      # - run:
      #     name: Sign Images
      #     command: |
