version: 2.1
executors:
  go-executor:
    docker:
      - image: arangodboasis/cimg-base:todo
jobs:
  build:
    executor: go-executor
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "$DOCKER_REGISTRY_PASSWORD" | base64 -d | docker login -u "$DOCKER_REGISTRY_USER" --password-stdin "$DOCKER_REGISTRY_HOST"
      - run: ./build-images.sh
      - slack/notify:
          event: fail
          template: basic_fail_1

orbs:
  slack: circleci/slack@4.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: arangodboasis

