version: 2.1

orbs:
  sonar: hubci/sonar@1.0.0
  cimg-orb: circleci/cimg-orb@0.1.3

workflows:
  main:
    jobs:
      - build-and-deploy:
          context: cimg-publishing

jobs:
  build-and-deploy:
    docker:
      - image: cimg/base:2022.04
    steps:
      - checkout
      - setup_remote_docker:
          version: "20.10.12"
      - cimg-orb/build-images:
          working-dir: ./
      - cimg-orb/push-images:
          working-dir: ./
          publish-branch: main
          image: cimg/go
      - when:
          condition:
            equal: [main, << pipeline.git.branch >>]
          steps:
          - sonar/install:
              version: "0.15.0"
          - sonar/update-readme:
              image: cimg/go
