version: 2.1

orbs:
  cimg: circleci/cimg@0.3.0

workflows:
  main-wf:
    jobs:
      - cimg/build-and-deploy:
          name: "Staging"
          docker-namespace: ccitest
          docker-repository: golang
          publish-branch: test
          filters:
            branches:
              ignore:
                - main
          context: cimg-publishing
      - cimg/build-and-deploy:
          name: "Deploy"
          docker-repository: go
          filters:
            branches:
              only:
                - main
          context: cimg-publishing
