version: 2.1

orbs:
  sonar: hubci/sonar@1.0.0
  cimg-orb: circleci/cimg-orb@0.1.2

workflows:
  main:
    jobs:
      - cimg-orb/build-and-deploy:
          working-dir: ./
          publish-branch: main
          image: cimg/go
  update-readme:
    when:
      equal: [main, << pipeline.git.branch >>]
    jobs:
      - sonar/update-readme:
          version: "0.15.0"
          image: cimg/go
          context: cimg-publishing
